# created pod 

apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:
    env: dev
    dc: IN

spec:
  containers:
  - name: "mycon1"
    image: "vimal13/apache-webserver-php"

----------------------------------------------------------------------------
# created pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

-----------------------------------------------------------------------------------------

#created pod with pvc

apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:
    env: dev
    dc: IN

spec:
  containers:
  - name: "mycon1"
    image: "vimal13/apache-webserver-php"
    volumeMounts:
         - name: web-vol1
           mountPath:  /var/www/html
  volumes:
     - name: web-vol1 
       persistentVolumeClaim: 
         claimName: mypvc1
--------------------------------------------------------------------------------------
